name: Ruby

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - head

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: Swatinem/rust-cache@v2
    - name: Run build task
      run: bundle exec rake install
      continue-on-error: true
    - run: ls vendor/bundle/ruby/3.2.0/gems/
    - name: Benchmark
      run: bundle exec ruby benchmark.rb
